"""add deleted_at to usuarios

Revision ID: 1381d457780b
Revises: e2abe38a5ceb
Create Date: 2026-04-03 19:27:39.042147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1381d457780b'
down_revision: Union[str, Sequence[str], None] = 'e2abe38a5ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'deleted_at')
    # ### end Alembic commands ###
