"""added card table and user relantioship to cards

Revision ID: d4e059c6517f
Revises: 1381d457780b
Create Date: 2026-05-06 13:40:24.904767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e059c6517f'
down_revision: Union[str, Sequence[str], None] = '1381d457780b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('cards', sa.Column('user_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'cards', 'usuarios', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'user_id')
    # ### end Alembic commands ###
