"""Added current streak variable to user table

Revision ID: fb8e0f341762
Revises: d4e059c6517f
Create Date: 2026-05-11 15:39:34.720513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8e0f341762'
down_revision: Union[str, Sequence[str], None] = 'd4e059c6517f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('current_streak', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###

    op.execute("UPDATE usuarios SET current_streak = 0 WHERE current_streak IS NULL")





def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'current_streak')
    # ### end Alembic commands ###
